### ISSUE TITLE
misspelled keybind description

### ISSUE THREAD

**Issue by TH3IIS** [esx-framework/esx_animations#11]
Stop Anmimation should be 'Stop Animation'

https://github.com/esx-framework/esx_animations/blob/96d74fda6680e3a5219357b812a6d195734fb13d/client/main.lua#L91

**Comment by TheFantomas** [comment]
Fixed in https://github.com/esx-framework/esx_animations/commit/c2132ac1e8073bc03542b9b0517b28ee515b71db
